// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "@/lib/env";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let _client: ReturnType<typeof createClient<Database>> | null = null;

function getSupabaseClient() {
  if (!_client) {
    _client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  }
  return _client;
}

export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop) {
    const realClient = getSupabaseClient();
    const val = (realClient as any)[prop];
    if (typeof val === "function") {
      return (...args: any[]) => (realClient as any)[prop](...args);
    }
    return val;
  },
});
